on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

name: Test

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            
            - name: Install Packages
              run: npm ci
            
            - name: Tests
              run: npm run coverage

            - name: Upload Coverage to CodeCov
              uses: codecov/codecov-action@v3